# Generated by Django 5.0.1 on 2025-10-17 10:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('MODULE_UPDATED', 'Module Updated')], max_length=50)),
                ('payload', models.JSONField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'db_table': 'rbac_outbox_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Processed Event',
                'verbose_name_plural': 'Processed Events',
                'db_table': 'rbac_processed_event',
                'ordering': ['processed_at'],
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField(db_collation='case_insensitive', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules',
                'managed': True,
                'indexes': [models.Index(fields=['name'], name='idx_module_name')],
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permission_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('action', models.TextField(db_collation='case_insensitive')),
                ('scope_hint', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='rbac.modules')),
            ],
            options={
                'db_table': 'permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField(db_collation='case_insensitive', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
                'indexes': [models.Index(fields=['name'], name='idx_role_name')],
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('role_permission_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='rbac.permissions')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='rbac.roles')),
            ],
            options={
                'db_table': 'role_permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('role_hierarchy_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('child_role', models.ForeignKey(db_column='child_role_id', on_delete=django.db.models.deletion.CASCADE, related_name='child_roles', to='rbac.roles')),
                ('parent_role', models.ForeignKey(db_column='parent_role_id', on_delete=django.db.models.deletion.CASCADE, related_name='parent_roles', to='rbac.roles')),
            ],
            options={
                'db_table': 'role_hierarchy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user_role_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('is_delegated', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='rbac.roles')),
            ],
            options={
                'db_table': 'user_roles',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='permissions',
            index=models.Index(fields=['module', 'action'], name='idx_module_action'),
        ),
        migrations.AddConstraint(
            model_name='permissions',
            constraint=models.UniqueConstraint(fields=('module', 'action'), name='unique_module_action'),
        ),
        migrations.AddIndex(
            model_name='rolepermissions',
            index=models.Index(fields=['role', 'permission'], name='idx_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='rolepermissions',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddIndex(
            model_name='rolehierarchy',
            index=models.Index(fields=['parent_role', 'child_role'], name='idx_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='rolehierarchy',
            constraint=models.UniqueConstraint(fields=('parent_role', 'child_role'), name='unique_parent_child'),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['user_id', 'role'], name='idx_user_role'),
        ),
        migrations.AddConstraint(
            model_name='userroles',
            constraint=models.UniqueConstraint(fields=('user_id', 'role'), name='unique_user_role'),
        ),
    ]
