# Generated by Django 5.0.1 on 2025-10-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutboxEvent',
        ),
        migrations.DeleteModel(
            name='ProcessedEvent',
        ),
        migrations.AddField(
            model_name='userroles',
            name='organization_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
